#!/bin/bash
pid=`pidof java`
if [[ $pid != "" ]]; then
  printf "Stopping Minecraft Server. This will take time."
  kill -SIGHUP $pid
fi
while [[ $pid != "" ]]; do
  pid=`pidof java`
  sleep 3
  printf "."
done
echo
echo "Done. Minecraft has been stopped safely."
