#!/bin/bash
if [[ $EUID -ne 0 ]]; then
  echo "ERROR: This script must be run as root" 2>&1
  exit 1
fi
pid=`pidof java`
if [[ $pid != "" ]]; then
  printf "Minecraft is running. Waiting."
  kill -SIGHUP $pid
fi
while [[ $pid != "" ]]; do
  pid=`pidof java`
  sleep 3
  printf "."
done
echo
echo "Rebooting."
/sbin/reboot
